# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Pi Plotter
email: mattmerr47@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  The endeavors of Matthew Merrill.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.piplotter.com" # the base hostname & protocol for your site
twitter_username: mattmerr47
github_username:  MatthewMerrill

defaults:
  -
    scope:
      path: "raspi"
      type: "posts"
    values:
      layout: "post"

sects:
  - Blog:
    title: 'Blog'
    description: 'Random Ramblings of a Developer'
    url: '/blog/'
  - RasberryPi:
    title: 'Raspberry Pi'
    description: 'Assorted Electronics / Pen Plotting projects'
    url: '/raspberrypi/'
  - Minecraft:
    title: 'Minecraft'
    description: 'Modding / Server Plugin / API tutorials'
    url: '/minecraft/'
    
# Build settings
markdown: kramdown
permalink: /:categories/:title/
