# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Matthew Merrill
email: mattmerr47@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Here you can find my latest endeavors from Algorithm Competitions to Raspberry Pi and everything between.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://MatthewMerrill.GitHub.io" # the base hostname & protocol for your site
twitter_username: mattmerr47
github_username:  MatthewMerrill

# Build settings
markdown: kramdown
